# Generated by Django 4.2.4 on 2023-10-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='del_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_name', models.CharField(max_length=100)),
                ('del_email', models.EmailField(max_length=254, unique=True)),
                ('del_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('res_email', models.EmailField(max_length=254, unique=True)),
                ('res_password', models.CharField(max_length=32)),
            ],
        ),
    ]
