# Generated by Django 4.2.4 on 2023-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0002_del_agent_restaurant_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishes_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant_d',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
