# Generated by Django 4.2.4 on 2023-10-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0003_dishes_d_restaurant_d_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes_d',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodomania.restaurant_d'),
        ),
    ]
