# Generated by Django 4.2.4 on 2023-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0004_dishes_d_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes_d',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
