# Generated by Django 4.2.4 on 2023-10-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0006_alter_dishes_d_image_alter_restaurant_d_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_d',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantsimages/'),
        ),
    ]
