# Generated by Django 4.2.4 on 2023-10-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0007_alter_restaurant_d_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_dets', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodomania.customer_d')),
                ('dishes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodomania.dishes_d')),
            ],
        ),
    ]
