# Generated by Django 4.2.4 on 2023-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
