# Generated by Django 4.2.4 on 2023-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodomania', '0010_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='Not Paid', max_length=20),
        ),
    ]
